### ISSUE TITLE
_unsemantic-vars Quotes + Unexpected Symbol

### ISSUE THREAD

**Issue by iathen** [nathansmith/unsemantic#67]
Hello, I'm not familiar with this project; I tried it today for the first time and I run across some syntax errors. When I load the stylesheet folder, most files are red, so I didn't read into that. Instead I loaded the .scss 's and there I found just one file with syntax errors, specifically "_unsemantic-vars.scss". The problem is that it doesn't ignore the " if you put a \ before (i.e. \" ). So this command
*width: unquote("expression(Math.floor(#{$decimal} * (this.parentNode.offsetWidth - parseFloat(this.parentNode.currentStyle.paddingLeft) - parseFloat(this.parentNode.currentStyle.paddingRight))) + \"px\")");
equals 
*width: unquote("expression(Math.floor(#{$decimal} * (this.parentNode.offsetWidth - parseFloat(this.parentNode.currentStyle.paddingLeft) - parseFloat(this.parentNode.currentStyle.paddingRight))) + "px")");

and this creates a lot of syntax errors. I tried to fix it with 
*width: unquote("expression(Math.floor(#{$decimal} * (this.parentNode.offsetWidth - parseFloat(this.parentNode.currentStyle.paddingLeft) - parseFloat(this.parentNode.currentStyle.paddingRight))) + 'px')");

The syntax error is gone, but 2 more syntax errors pop up lower (x Unexpected symbol found (where x = * or $ or % etc)). If I comment out the 2 problematic sentences, I get 2 more errors (and continues like that for the rest).

As I said, I'm not familiar with the project, so I can't really help with a solution. I didn't even know that sass existed before today. I just thought to let you know, in case this is really a bug and not something that my computer produced.

**Comment by nathansmith** [comment]
This has to do with the embedded JS (aka "CSS expression"), for IE7 to simulate `box-sizing: border-box`.

I just changed the escaped `\"` to regular single quotes today. I am not seeing any Sass compilation errors, though. Which version of Sass are you using?
