### ISSUE TITLE
Add $container-gutter var

### ISSUE THREAD

**Issue by jkuss** [nathansmith/unsemantic#70]
I recently came across an issue where I needed a different gutter for the grid-container. To fix this I added with the rest of the few vars:
`$container-gutter: $gutter-half !default;`

and line 180
```
// Set if gutter is non-zero.
    @if $container-gutter != 0 {
      padding-left: $container-gutter;
      padding-right: $container-gutter;
    }
```

**Comment by nathansmith** [comment]
This has been added. Sorry it took so long. :(
