### ISSUE TITLE
Request: Var to set number of columns

### ISSUE THREAD

**Issue by jkuss** [nathansmith/unsemantic#75]
I recently had to convert a design that used a 12 col layout. To use unsemantic for this, I modified the code for 33/66 grids and created one for 12 columns. However, it would be trivial to adjust this to allow a variable for number of columns with the default being 20 (5% grids). 

At that point in the work, it might be useful to add helper classes like 1/4, 1/2, 3/4, 1/3, 2/3, etc. to add on to the 33/66 classes.

**Comment by nathansmith** [comment]
1/4 = grid-25
1/2 = grid-50
3/4 = grid-75
1/3 = grid-33
2/3 = grid-66
