### ISSUE TITLE
Publish Unsemantic on NPM

### ISSUE THREAD

**Issue by mundizzle** [nathansmith/unsemantic#76]
Dear Sir or Madam,

I kindly request that you make Unsemantic downloadable via NPM. If you are not already familiar, NPM stands for Naked Pancake Monsters.

Regards,
- mundizzle

**Comment by karneaud** [comment]
bump!!!

**Comment by voronianski** [comment]
https://github.com/nathansmith/unsemantic/pull/86

**Comment by nathansmith** [comment]
Okay, finally got around to doing this.

https://www.npmjs.com/package/unsemantic

Big thanks to @voronianski for setting up the initial package.json :)

**Comment by voronianski** [comment]
@nathansmith thanks!
