### ISSUE TITLE
Warning using unquote()

### ISSUE THREAD

**Issue by nicooprat** [nathansmith/unsemantic#77]
Hi, I'm using **Codekit** with **Sass 3.4.10** + **Libsass 3.1** and I'm having a lot of this kind of warning :

````
DEPRECATION WARNING: Passing null, a non-string value, to unquote()
will be an error in future versions of Sass.
````

Do you have a workaround ? I tried to modify some code of Unsemantic but without success. I'd rather not to disable warnings. Thanks !

**Comment by pixelize** [comment]
Same problem on one of my project. unquote args has to be quoted
unquote('something');

**Comment by shawn458** [comment]
A solution to this is to create a safe version of unquote. It only gets called if it's a string. 

Add this function:
@function safe-unquote($param) {
  @return if(type-of($param) == string, unquote($param), $param);
}

Then, change all unquote() functions to safe-unquote() inside of _unsemantic-vars.scss.

**Comment by ctumolosus** [comment]
I was having issue parsing unsemantic through libsass as well and @shawn458 solution worked for me.

**Comment by nicooprat** [comment]
I can confirm it works, thanks @shawn458. The function can be simply copy/pasted in the beginning of `_unsemantic-vars.scss`.
