### ISSUE TITLE
grid-container fixed-width +padding 

### ISSUE THREAD

**Issue by sjamesmccarthy** [nathansmith/unsemantic#78]
This really isn't an issue but more of a question.
Why is grid-container fixed max-width at 1200px and include 10px left/right padding when everythign else is % based? 

It seems that if this was  fully responsive it would by default support full-width 100% with 0 padding on left/right on the main grid-container element.

.grid-container {
  margin-left: auto;
  margin-right: auto;
  width: 100%;
}

Other than this small fixed-pixel uniqueness it's great :-)

**Comment by nathansmith** [comment]
Sorry for the delayed reply.

That `max-width` is simply to keep the line lengths from getting too long, if someone is viewing a page with their browser at full width (on a 27" monitor, etc).

The gutter for all grid units is set in pixels (including the container's outer padding).

This is to create gutters with visual consistency, roughly equivalent (20px) to the default line-height on the page. This 20px is also the default `margin-bottom` on all block level elements, such as `<p>` (as set in text.css).
