### ISSUE TITLE
Sass Deprecation Warnig: a non-string value, to unquote() will be an error in future versions of Sass.

### ISSUE THREAD

**Issue by luanmuniz** [nathansmith/unsemantic#79]
Im receiving this message:

```
DEPRECATION WARNING: Passing 0.66667, a non-string value, to unquote() will be an error in future versions of Sass.
        on line 64 of .../grid/unsemantic-vars.scss, in `ie7-pull'
        from line 314 of .../grid/unsemantic-vars.scss, in `unsemantic-grid-placeholders'
```

Any ideas? I tried to update my sass but i still have this message.
Compass v1.0.3
Sass v3.4.13

**Comment by nathansmith** [comment]
Sorry for the delayed reply.

This should be fixed now, as of this commit…

https://github.com/nathansmith/unsemantic/commit/d20c50061e51914d9aaa7b5a3b5e6ef7ff8f462a

**Comment by nathansmith** [comment]
Basically, I was calling `unquote` in case someone had passed a value as a string…

    // Would convert "10" into 10.
    $foo: unquote($foo);

But, it wasn't really necessary, as I wasn't passing strings around anyway.

:)

It used to be a "best practice" to call `unquote` on incoming variables, but I guess now it's not.
