### ISSUE TITLE
DEPRECATION WARNING: Passing 0.5, a non-string value, to unquote() will be an error in future versions of Sass on line 51 of _unsemantic-vars.scss

### ISSUE THREAD

**Issue by karneaud** [nathansmith/unsemantic#88]
Kept getting this error when compiling sass using the latest gulp and sass.

**Comment by nathansmith** [comment]
I believe this should be fixed, as described in this ticket…

https://github.com/nathansmith/unsemantic/issues/82

Are you still running into this, even with the latest code?

**Comment by karneaud** [comment]
odd I do have ie-7 support to false and I installed unsemantic#1.0.2 bower_components/unsemantic. Will look into it. Thanks!

**Comment by karneaud** [comment]
Fixed it using the solution you had opposed @nathansmith. Though the fixed did not come with the bower install 1.0.2. Is this the latest bower package?

**Comment by nathansmith** [comment]
I don't use Bower personally, and was hoping that it would just die off.

But, I guess I probably need to "tag" a release for Bower?

**Comment by karneaud** [comment]
I guess :-/

**Comment by nathansmith** [comment]
I'll leave this issue open, I didn't mean for you to close it.

My reply wasn't meant as a "won't fix" response.

Just that, with everything shifting towards NPM (away from Bower), and not using Bower myself, I tend not to remember to do the steps to "tag" things.

**Comment by nathansmith** [comment]
Okay, this should be fixed in tag `1.0.3` now…

https://github.com/nathansmith/unsemantic/tree/1.0.3

Let me know if that works for you, or not. Thanks.

**Comment by freefri** [comment]
Fixed for me using the tag `1.0.3` with bower
