### ISSUE TITLE
Inherit custom css classes from Grid Component

### ISSUE THREAD

**Issue by leeeandroo** [nathansmith/unsemantic#94]
I started use the unsemantic react solution, but I miss a way from Grid inherit the css classes from Grid Component. I didn`t see a way to do this, it always override my custom css classes with unsemantic classes.

I would like to propose something like this on grid.js:

```
if(this.props.className)
      className = this.props.className.split(' ')
```

Does it make sense for you? Am I missing something that currently available to do this?

Thanks,

**Comment by nathansmith** [comment]
This functionality has been added…

https://github.com/nathansmith/unsemantic/commit/f46cc04bbc0aebbcab6dbd3c74f443198efc7bd6
